#server:
#  port: 8080
#spring:
#  application:
#    name: hbt-project-ability
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#management:
#  endpoint:
#    web:
#      exposure:
#        include: "*"